### ISSUE TITLE
version of the packages

### ISSUE THREAD

**Issue by BeatrizGSC** [aqqush/CT_BET#3]
Could you please indicate the full list of packages requirement indicating the version. 
For example, using `pip freeze`.
Thank you very much for advance.

**Comment by aqqush** [comment]
Please let me know if you see any library issue but I don't think any difference in library version would create any issue.

**Comment by novellisa** [comment]
Hello, could you please provide the versions of the required packages?

_E.g._, using tensorflow version 2.12.0, I am currently getting the following error:
`ImportError: cannot import name 'multi_gpu_model' from 'keras.utils'`

Downgrading keras version to 2.2.4 makes other issues arise. It would thus be very helpful to be able to reproduce your original environment by getting the version of the packages you used.
Thank you in advance.
