### ISSUE TITLE
question about data format

### ISSUE THREAD

**Issue by seungjunlee96** [aqqush/CT_BET#5]
Hi,

Thank you for sharing your great work! 

How can I use your code if I have access to only DICOM files of axial slices?

Thanks

**Comment by aqqush** [comment]
You just need to change the lines in the load training data function in the model_CT_SS.py. You can use DICOM load library such as pydicom or simpleITK to load Dicom images.
def loadTrainingData(self,images_path,labels_path, each):
        images = nb.load(os.path.join(images_path,each)).get_data() 
        labels = nb.load(os.path.join(labels_path,each)).get_data()
        affine = nb.load(os.path.join(images_path,each)).get_affine()        
        
        if self.dataAugmentation:
            images,labels = self.datagen.generate(images,labels,self.afold,affine)
        [self.img_rows,self.img_cols,self.numImgs] = images.shape
        
        images = images.transpose(2,0,1).reshape(self.numImgs, self.img_rows,self.img_cols,1).astype(self.dtype)
        labels = labels.transpose(2,0,1).reshape(self.numImgs, self.img_rows,self.img_cols,1).astype(self.dtypeL)
        return images,labels, affine
